### ISSUE TITLE
(Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :data_does_not_match_schema}

### ISSUE THREAD

**Issue by Yamilquery** [CJPoll/avro_ex#12]
I have an issue when I try to encode a schema using the `AvroEx.encode(schema, payload)`

This is my schema object:

```
%AvroEx.Schema{
  context: %AvroEx.Schema.Context{
    names: %{
      "command.Payload" => %AvroEx.Schema.Record{
        aliases: [],
        doc: nil,
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: nil,
            id: nil,
            name: "message",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          }
        ],
        id: nil,
        metadata: %{},
        name: "Payload",
        namespace: nil,
        qualified_names: ["command.Payload"]
      },
      "command.test" => %AvroEx.Schema.Record{
        aliases: [],
        doc: "A Test Publish Event",
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "standard event metadata",
            id: nil,
            name: "meta",
            type: "seven.cloud.services.event_metadata"
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "payload record",
            id: nil,
            name: "payload",
            type: %AvroEx.Schema.Record{
              aliases: [],
              doc: nil,
              fields: [
                %AvroEx.Schema.Record.Field{
                  aliases: [],
                  default: nil,
                  doc: nil,
                  id: nil,
                  name: "message",
                  type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
                }
              ],
              id: nil,
              metadata: %{},
              name: "Payload",
              namespace: nil,
              qualified_names: ["command.Payload"]
            }
          }
        ],
        id: nil,
        metadata: %{},
        name: "command.test",
        namespace: "command",
        qualified_names: ["command.test"]
      },
      "seven.cloud.services.callback_topic" => %AvroEx.Schema.Record{
        aliases: [],
        doc: nil,
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: nil,
            id: nil,
            name: "topic",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
              ]
            }
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: nil,
            id: nil,
            name: "partition",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Primitive{metadata: %{}, type: :integer}
              ]
            }
          }
        ],
        id: nil,
        metadata: %{},
        name: "callback_topic",
        namespace: nil,
        qualified_names: ["seven.cloud.services.callback_topic"]
      },
      "seven.cloud.services.event_metadata" => %AvroEx.Schema.Record{
        aliases: [],
        doc: nil,
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "id of this mesage",
            id: nil,
            name: "message_id",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "name of the emitting service",
            id: nil,
            name: "emitter_service",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "uuid of the emitting service",
            id: nil,
            name: "emitter_service_id",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "uuid of waiting callback in the emitting service",
            id: nil,
            name: "callback_id",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
              ]
            }
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "name of the event. Even if the name is defined elsewhere meta should always include the event name",
            id: nil,
            name: "message_name",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "UTC time stamp of event publication",
            id: nil,
            name: "timestamp",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{ 
            aliases: [],
            default: "null",
            doc: "assert callback message topic & partition",
            id: nil,
            name: "callback_topic",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Record{
                  aliases: [],
                  doc: nil,
                  fields: [
                    %AvroEx.Schema.Record.Field{
                      aliases: [],
                      default: nil,
                      doc: nil,
                      id: nil,
                      name: "topic",
                      type: %AvroEx.Schema.Union{
                        possibilities: [
                          %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                          %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
                        ]
                      }
                    },
                    %AvroEx.Schema.Record.Field{
                      aliases: [],
                      default: nil,
                      doc: nil,
                      id: nil,
                      name: "partition",
                      type: %AvroEx.Schema.Union{
                        possibilities: [
                          %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                          %AvroEx.Schema.Primitive{
                            metadata: %{},
                            type: :integer
                          }
                        ]
                      }
                    }
                  ],
                  id: nil,
                  metadata: %{},
                  name: "callback_topic", 
                  namespace: nil,
                  qualified_names: ["seven.cloud.services.callback_topic"]
                }
              ]
            }
          }
        ],
        id: nil,
        metadata: %{},
        name: "event_metadata",
        namespace: "seven.cloud.services",
        qualified_names: ["seven.cloud.services.event_metadata"]
      }
    }
  },
  schema: %AvroEx.Schema.Union{
    possibilities: [
      %AvroEx.Schema.Record{
        aliases: [],
        doc: nil,
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "id of this mesage",
            id: nil,
            name: "message_id",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "name of the emitting service",
            id: nil,
            name: "emitter_service",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "uuid of the emitting service",
            id: nil,
            name: "emitter_service_id",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "uuid of waiting callback in the emitting service",
            id: nil,
            name: "callback_id",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
              ]
            }
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "name of the event. Even if the name is defined elsewhere meta should always include the event name",
            id: nil,
            name: "message_name",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "UTC time stamp of event publication",
            id: nil,
            name: "timestamp",
            type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: "null",
            doc: "assert callback message topic & partition",
            id: nil,
            name: "callback_topic",
            type: %AvroEx.Schema.Union{
              possibilities: [
                %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                %AvroEx.Schema.Record{
                  aliases: [],
                  doc: nil,
                  fields: [
                    %AvroEx.Schema.Record.Field{
                      aliases: [],
                      default: nil,
                      doc: nil,
                      id: nil,
                      name: "topic",
                      type: %AvroEx.Schema.Union{
                        possibilities: [
                          %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                          %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
                        ]
                      }
                    },
                    %AvroEx.Schema.Record.Field{
                      aliases: [],
                      default: nil,
                      doc: nil,
                      id: nil,
                      name: "partition",
                      type: %AvroEx.Schema.Union{
                        possibilities: [
                          %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
                          %AvroEx.Schema.Primitive{
                            metadata: %{},
                            type: :integer
                          }
                        ]
                      }
                    }
                  ],
                  id: nil,
                  metadata: %{},
                  name: "callback_topic",
                  namespace: nil,
                  qualified_names: ["seven.cloud.services.callback_topic"]
                }
              ]
            }
          }
        ],
        id: nil,
        metadata: %{},
        name: "event_metadata",
        namespace: "seven.cloud.services",
        qualified_names: ["seven.cloud.services.event_metadata"]
      },
      %AvroEx.Schema.Record{
        aliases: [],
        doc: "A Test Publish Event",
        fields: [
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "standard event metadata",
            id: nil,
            name: "meta",
            type: "seven.cloud.services.event_metadata"
          },
          %AvroEx.Schema.Record.Field{
            aliases: [],
            default: nil,
            doc: "payload record",
            id: nil,
            name: "payload",
            type: %AvroEx.Schema.Record{
              aliases: [],
              doc: nil,
              fields: [
                %AvroEx.Schema.Record.Field{
                  aliases: [],
                  default: nil,
                  doc: nil,
                  id: nil,
                  name: "message",
                  type: %AvroEx.Schema.Primitive{metadata: %{}, type: :string}
                }
              ],
              id: nil,
              metadata: %{},
              name: "Payload",
              namespace: nil,
              qualified_names: ["command.Payload"]
            }
          }
        ],
        id: nil,
        metadata: %{},
        name: "command.test",
        namespace: "command",
        qualified_names: ["command.test"]
      }
    ]
  }
}
```

This is my payload object:

```
%{      
  "meta" => %{
    "callback_id" => nil,
    "callback_topic" => nil,
    "emitter_service" => "SampleService",
    "emitter_service_id" => "SampleHost",
    "message_id" => "XDITQOMvUW5Fjzj6~COay",
    "message_name" => "command.test",
    "timestamp" => "2019-03-06 21:06:42.149636Z"
  },
  "payload" => %{"message" => "Hello World"}
}
```

And this is the error that I get:

```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :data_does_not_match_schema, "null", %AvroEx.Schema.Union{possibilities: [%AvroEx.Schema.Primitive{metadata: %{}, type: nil}, %AvroEx.Schema.Record{aliases: [], doc: nil, fields: [%AvroEx.Schema.Record.Field{aliases: [], default: nil, doc: nil, id: nil, name: "topic", type: %AvroEx.Schema.Union{possibilities: [%AvroEx.Schema.Primitive{metadata: %{}, type: nil}, %AvroEx.Schema.Primitive{metadata: %{}, type: :string}]}}, %AvroEx.Schema.Record.Field{aliases: [], default: nil, doc: nil, id: nil, name: "partition", type: %AvroEx.Schema.Union{possibilities: [%AvroEx.Schema.Primitive{metadata: %{}, type: nil}, %AvroEx.Schema.Primitive{metadata: %{}, type: :integer}]}}], id: nil, metadata: %{}, name: "callback_topic", namespace: nil, qualified_names: ["seven.cloud.services.callback_topic"]}]}}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Ecto.Date, Ecto.DateTime, Ecto.Time, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) /private/tmp/elixir-20180825-41637-j0b7x7/elixir-1.7.3/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir) lib/enum.ex:2777: anonymous fn/3 in Enum.join/2
    (elixir) lib/enum.ex:1925: Enum."-join/2-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1925: Enum.join/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    lib/avro_ex/encode.ex:125: AvroEx.Encode.do_encode/3
    lib/avro_ex/encode.ex:146: AvroEx.Encode.do_encode/3
    lib/avro_ex/encode.ex:16: AvroEx.Encode.encode/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (iex) lib/iex/evaluator.ex:249: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:229: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:207: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4
    (iex) lib/iex/pry.ex:64: IEx.Pry.pry/2
    lib/test_support/mock_schema_registry.ex:36: KaufmannEx.TestSupport.MockSchemaRegistry.encode_event/2
    lib/test_support/mock_bus.ex:107: KaufmannEx.TestSupport.MockBus.given_event/3
    test/event_handler_test.exs:7: Sample.EventHandlerTest."test Events Can Be published & observed"/1
```

**Comment by gerbal** [comment]
`"default": "null"` should be `"default": null`

**Comment by Yamilquery** [comment]
Thank you very much @gerbal , it works!
